sudo: false
language: generic

global:
  env:
    - COMMIT_AUTHOR_EMAIL: "f.zapata@esciencecenter.nl"

install:
  # Install python
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda False
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Install virtual enviroment 
  - conda install -c anaconda hdf5
  - conda install -c rdkit rdkit

  # Install qmflows package
  - pip install git+https://github.com/SCM-NV/plams@master#egg=plams-1.2 --upgrade
  - pip install .[test,doc]
  
script:
  # Run the unitary tests excluding the expensive computations
  - py.test -m "not (slow or long)" --cov=qmflows test
  - echo "building gh-pages documentation"
    cd doc
    bash ./deploy.sh

branches:
  only:
   - master
