name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        version: [3.6, 3.7, 3.8, 3.9]
        special: ['']
        include:
          - os: ubuntu-latest
            special: 'pre-release'
            version: 3.9
          - os: ubuntu-latest
            special: 'no RDKit'
            version: 3.9

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: git checkout
      uses: actions/checkout@v2

    - name: git ls-files
      run: git ls-files --full-name --recurse-submodules

    - name: Install cp2k
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install cp2k --fix-missing

    - name: Info CP2K
      if: matrix.os == 'ubuntu-latest'
      run: cp2k.popt --version

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        conda-channels: anaconda, conda-forge

    - name: Install dependencies
      shell: bash
      run: |
        case "${{ matrix.special }}" in
          "pre-release")
            conda create -n test -c conda-forge python=${{ matrix.version }} rdkit nbsphinx jupyter pandoc
            source $CONDA/bin/activate test
            pip install --pre -e .[test] --upgrade --force-reinstall
            ;;
          "no RDKit")
            conda create -n test -c conda-forge python=${{ matrix.version }} nbsphinx jupyter pandoc
            source $CONDA/bin/activate test
            pip install -e .[test]
            ;;
          *)
            conda create -n test -c conda-forge python=${{ matrix.version }} rdkit nbsphinx jupyter pandoc
            source $CONDA/bin/activate test
            pip install -e .[test]
            ;;
        esac

    - name: Conda info
      run: |
        source $CONDA/bin/activate test
        conda info

    - name: Conda list
      run: conda list -n test

    - name: Test with pytest
      shell: bash
      run: |
        source $CONDA/bin/activate test

        case "${{ matrix.special }}" in
          "no RDKit")
            pytest -m 'not (slow or long)' test ;;
          *)
            pytest -m 'not (slow or long)' ;;
        esac

    - uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        name: codecov-umbrella
