name: Tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CP2K_DATA_DIR: "${{ github.workspace }}/cp2k/data"

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        special: ['']
        include:
          - os: ubuntu-latest
            special: ['pre-release', '']
            version: '3.10'
          - os: ubuntu-latest
            special: ['no optional', '']
            version: '3.10'
          - os: ubuntu-latest
            special: ['CP2K', '6.1']
            version: '3.10'
          - os: ubuntu-latest
            special: ['CP2K', '7.1']
            version: '3.10'
          - os: ubuntu-latest
            special: ['CP2K', '8.2']
            version: '3.10'
          - os: ubuntu-latest
            special: ['CP2K', '9.1']
            version: '3.10'
          - os: ubuntu-latest
            special: ['CP2K', '2022.1']
            version: '3.10'
    steps:
    - uses: actions/checkout@v3

    - name: Install cp2k
      if: matrix.special[0] == 'CP2K'
      run: |
        bash scripts/download_cp2k.sh x86_64 ${{ matrix.special[1] }}

    - name: Info CP2K
      if: matrix.special[0] == 'CP2K'
      run: cp2k.ssmp --version

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true

    - name: Install dependencies
      run: |
        case "${{ matrix.special[0] }}" in
          "pre-release")
            conda create -n test -c conda-forge python=${{ matrix.version }} nbsphinx jupyter pandoc
            source $CONDA/bin/activate test
            pip install --pre -e .[test] --upgrade --force-reinstall
            pip uninstall plams -y; pip install git+https://github.com/SCM-NV/PLAMS@master --upgrade
            pip install git+https://github.com/NLeSC/noodles@master --upgrade
            ;;
          "no optional")
            conda create -n test -c conda-forge python=${{ matrix.version }}
            source $CONDA/bin/activate test
            pip install -e .[test_no_optional]
            ;;
          *)
            conda create -n test -c conda-forge python=${{ matrix.version }} nbsphinx jupyter pandoc
            source $CONDA/bin/activate test
            pip install -e .[test]
            ;;
        esac

    - name: Conda info
      run: |
        source $CONDA/bin/activate test
        conda info

    - name: Conda list
      run: conda list -n test

    - name: Test with pytest
      run: |
        source $CONDA/bin/activate test
        case "${{ matrix.special[0] }}" in
          "no optional")
            pytest -m 'not (slow or long)' test ;;
          "CP2K")
            pytest -m '(slow or long)' ;;
          *)
            pytest -m 'not (slow or long)' ;;
        esac

    - uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        name: codecov-umbrella

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install linters
        run: pip install pydocstyle pycodestyle mypy "numpy>=1.21" pytest more_itertools types-PyYAML types-setuptools "pyparsing>=3.0.8"

      - name: Python info
        run: |
          which python
          python --version

      - name: Installed packages
        run: pip list

      - name: Run pycodestyle
        run: pycodestyle src test

      - name: Run pydocstyle
        run: pydocstyle src

      - name: Run mypy
        run: mypy src
        continue-on-error: true
