name: build with conda

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        version: [3.6, 3.7, 3.8, 3.9]
        special: ['']
        include:
          - os: ubuntu-latest
            special: 'pre-release'
            version: 3.9
          - os: ubuntu-latest
            special: 'no RDKit'
            version: 3.9

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: Install cp2k
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt list -a cp2k
        sudo apt install cp2k --fix-missing

    - name: Info CP2K
      if: matrix.os == 'ubuntu-latest'
      run: cp2k.popt --version

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        conda-channels: anaconda

    - name: Install dependencies
      if: matrix.special == ''
      run: |
        conda create -n test -c conda-forge python=${{ matrix.version }} h5py rdkit nbsphinx jupyter pandoc
        source $CONDA/bin/activate test
        pip install -e .[test]

    - name: Install dependencies (pre-release)
      if: matrix.special == 'pre-release'
      run: |
        conda create -n test -c conda-forge python=${{ matrix.version }} h5py rdkit nbsphinx jupyter pandoc
        source $CONDA/bin/activate test
        pip install --pre -e .[test] --upgrade --force-reinstall

    - name: Install dependencies (no RDKit)
      if: matrix.special == 'no RDKit'
      run: |
        conda create -n test -c conda-forge python=${{ matrix.version }} h5py nbsphinx jupyter pandoc
        source $CONDA/bin/activate test
        pip install -e .[test]

    - name: Conda info
      run: conda info

    - name: Conda list
      run: conda list -n test

    - name: Test with pytest
      if: matrix.special != 'no RDKit'
      run: |
        source $CONDA/bin/activate test
        pytest -m "not (slow or long)"

    - name: Test with pytest (no RDKit)
      if: matrix.special == 'no RDKit'
      run: |
        source $CONDA/bin/activate test
        pytest -m "not (slow or long)" test

    - uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        name: codecov-umbrella
