name: build with conda

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:  [macos-latest, ubuntu-latest]
        version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Optionally Install cp2k
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install cp2k

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        conda-channels: anaconda

    - name: Install dependencies
      run: conda create -n test -c conda-forge python=${{ matrix.version }} h5py rdkit nbsphinx jupyter

    - name: Install the package
      run: |
        source $CONDA/bin/activate test
        pip install -e .[test]

    - name: Conda info
      run: conda info

    - name: Conda list
      run: conda list -n test

    - name: Test with pytest
      run: |
        source $CONDA/bin/activate test
        pytest -m "not (slow or long)"

    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-umbrella
