name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        version: [3.6, 3.7, 3.8, 3.9]
        special: ['']
        include:
          - os: ubuntu-latest
            special: 'pre-release'
            version: 3.9
          - os: ubuntu-latest
            special: 'no optional'
            version: 3.9
          - os: ubuntu-latest
            special: 'slow'
            version: 3.9
          - os: ubuntu-latest
            special: 'CP2K 8.2'
            version: 3.9

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: Install cp2k
      if: matrix.os == 'ubuntu-latest'
      run: |
        case "${{ matrix.special }}" in
          "CP2K 8.2")
            git clone https://github.com/cp2k/cp2k
            cd cp2k
            git checkout tags/v8.2.0
            wget https://github.com/cp2k/cp2k/releases/download/v8.2.0/cp2k-8.2-Linux-x86_64.ssmp
            ln -s cp2k-8.2-Linux-x86_64.ssmp /usr/local/bin/cp2k.popt
            ln -s data /usr/share/cp2k
            ;;
          *)
            sudo apt install cp2k --fix-missing ;;
         esac

    - name: Info CP2K
      if: matrix.os == 'ubuntu-latest'
      run: |
        cp2k.popt --version

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        conda-channels: anaconda, conda-forge

    - name: Install dependencies
      shell: bash
      run: |
        case "${{ matrix.special }}" in
          "pre-release")
            conda create -n test -c conda-forge python=${{ matrix.version }} rdkit nbsphinx jupyter pandoc
            source $CONDA/bin/activate test
            pip install --pre -e .[test] --upgrade --force-reinstall
            ;;
          "no optional")
            conda create -n test -c conda-forge python=${{ matrix.version }}
            source $CONDA/bin/activate test
            pip install -e .[test_no_optional]
            ;;
          *)
            conda create -n test -c conda-forge python=${{ matrix.version }} rdkit nbsphinx jupyter pandoc
            source $CONDA/bin/activate test
            pip install -e .[test]
            ;;
        esac

    - name: Conda info
      run: |
        source $CONDA/bin/activate test
        conda info

    - name: Conda list
      run: conda list -n test

    - name: Test with pytest
      shell: bash
      run: |
        source $CONDA/bin/activate test
        export CP2K_DATA_DIR="/usr/share/cp2k"

        case "${{ matrix.special }}" in
          "no optional")
            pytest -m 'not (slow or long)' test ;;
          "slow")
            pytest -m '(slow or long)' ;;
          *)
            pytest -m 'not (slow or long)' ;;
        esac

    - uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        name: codecov-umbrella
