name: build with conda

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@master
    - name: Setup conda
      uses: s-weigand/setup-conda@master
      with:
        update-conda: true
        python-version: ${{ matrix.version }}
        conda-channels: anaconda
    - run: conda --version
    - run: python --version
    - run: |
        conda install -c conda-forge h5py rdkit
 
    - name: Install the package
      run: pip install -e .[test]
      env:
        CONDA_PREFIX: /usr/share/miniconda

    - name: Test with pytest
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: |
        pip install pytest pytest-cov
        pytest -m "not (slow or long)" test
